/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gsb;


import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Connection;

/**
 *
 * @author lmontay
 */
public class FenetreConsulter extends javax.swing.JFrame {
    private AccesBdD accesBdD;
    private UtilisateurDAO utilDAO;
    /**
     * Creates new form FenetreConsulter
     */
    public FenetreConsulter() {
        this.accesBdD = new AccesBdD();
        utilDAO = new UtilisateurDAO(accesBdD.getConnexion());
        initComponents();
        listerUtilisateurs();
    }
    
    private void listerUtilisateurs(){
        ArrayList<Utilisateur> util = utilDAO.getLesUtilisateurs(); 
        DefaultTableModel tableModel = (DefaultTableModel)tableUtilisateurs.getModel();
        tableModel.setRowCount(0);

        if (!util.isEmpty()){
            for (Utilisateur u1 : util) {
                Object[] Utilisateur = new Object[8];
                Utilisateur[0]=u1.getId();
                Utilisateur[1]=u1.getNom();
                Utilisateur[2]=u1.getPrenom();
                Utilisateur[3]=u1.getLogin();
                Utilisateur[4]=u1.getAdresse();
                Utilisateur[5]=u1.getCp();
                Utilisateur[6]=u1.getVille();
                Utilisateur[7]=u1.getDateEmbauche();
                tableModel.addRow(Utilisateur);
            }
        }
        tableUtilisateurs.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUtilisateurs = new javax.swing.JTable();
        jTextRecherche = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Consulter");

        tableUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "prenom", "login", "adresse", "cp", "ville", "dateEmbauche"
            }
        ));
        jScrollPane1.setViewportView(tableUtilisateurs);

        jTextRecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextRechercheFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextRechercheFocusLost(evt);
            }
        });
        jTextRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRechercheActionPerformed(evt);
            }
        });

        jButton1.setText("Ajouter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifier");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextRecherche)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(331, 331, 331))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jTextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRechercheActionPerformed
        String recherche = jTextRecherche.getText() + "%";

        try {
            String sql = "SELECT * FROM utilisateur WHERE nom LIKE ? OR prenom LIKE ? OR login LIKE ? OR id LIKE ? OR ville LIKE ? OR dateEmbauche LIKE ?";
            PreparedStatement statement = accesBdD.getConnexion().prepareStatement(sql);

            for (int i = 1; i <= 6; i++) {
                statement.setString(i, recherche);
            }
            ResultSet result = statement.executeQuery();

            DefaultTableModel tableModel = (DefaultTableModel) tableUtilisateurs.getModel();
            tableModel.setRowCount(0);

            while (result.next()) {
                Object[] util = new Object[9];
                util[0] = result.getString("id");
                util[1] = result.getString("nom");
                util[2] = result.getString("prenom");
                util[3] = result.getString("login");
                util[4] = result.getString("mdp");
                util[5] = result.getString("adresse");
                util[6] = result.getString("cp");
                util[7] = result.getString("ville");
                util[8] = result.getDate("dateEmbauche");

                tableModel.addRow(util);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccesBdD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextRechercheActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FenetreAjouter FenetreAjouter = new FenetreAjouter();
        FenetreAjouter.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //FenetreModifier.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextRechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRechercheFocusGained
        if (jTextRecherche.getText().equals("Rechercher : ")) {
        jTextRecherche.setText("");
        jTextRecherche.setForeground(Color.BLACK );
    }
    }//GEN-LAST:event_jTextRechercheFocusGained

    private void jTextRechercheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRechercheFocusLost
        if (jTextRecherche.getText().isEmpty()) {
        jTextRecherche.setText("Rechercher : ");
        jTextRecherche.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_jTextRechercheFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreConsulter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextRecherche;
    private javax.swing.JTable tableUtilisateurs;
    // End of variables declaration//GEN-END:variables

}
