/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gsb;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lmontay & mlefloch
 */
public class FenetreConsulter extends javax.swing.JFrame {
    private AccesBdD accesBdD;
    private UtilisateurDAO utilDAO;
    /**
     * Creates new form FenetreConsulter
     */
    public FenetreConsulter() {
        this.accesBdD = new AccesBdD();
        utilDAO = new UtilisateurDAO(accesBdD.getConnexion());
        initComponents();
        listerUtilisateurs();
    }
    
    private void listerUtilisateurs(){
        ArrayList<Utilisateur> util = utilDAO.getLesUtilisateurs(); 
        DefaultTableModel tableModel = (DefaultTableModel)tableUtilisateurs.getModel();
        tableModel.setRowCount(0);

        if (!util.isEmpty()){
            for (Utilisateur u1 : util) {
                Object[] Utilisateur = new Object[8];
                Utilisateur[0]=u1.getId();
                Utilisateur[1]=u1.getNom();
                Utilisateur[2]=u1.getPrenom();
                Utilisateur[3]=u1.getLogin();
                Utilisateur[4]=u1.getAdresse();
                Utilisateur[5]=u1.getCp();
                Utilisateur[6]=u1.getVille();
                Utilisateur[7]=u1.getDateEmbauche();
                tableModel.addRow(Utilisateur);
            }
        }
        tableUtilisateurs.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableUtilisateurs = new javax.swing.JTable();
        jTextRecherche = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Consulter");

        tableUtilisateurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "nom", "prenom", "login", "adresse", "cp", "ville", "dateEmbauche"
            }
        ));
        jScrollPane1.setViewportView(tableUtilisateurs);

        jTextRecherche.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextRechercheFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextRechercheFocusLost(evt);
            }
        });
        jTextRecherche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRechercheActionPerformed(evt);
            }
        });

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonRetour.setText("Retour");
        jButtonRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextRecherche)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButtonRetour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonModifier, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(331, 331, 331))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jTextRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonRetour, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextRechercheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRechercheActionPerformed
        String recherche = jTextRecherche.getText() + "%";

        try {
            String sql = "SELECT * FROM utilisateur WHERE nom LIKE ? OR prenom LIKE ? OR login LIKE ? OR id LIKE ? OR ville LIKE ? OR dateEmbauche LIKE ?";
            PreparedStatement statement = accesBdD.getConnexion().prepareStatement(sql);

            for (int i = 1; i <= 6; i++) {
                statement.setString(i, recherche);
            }
            ResultSet result = statement.executeQuery();

            DefaultTableModel tableModel = (DefaultTableModel) tableUtilisateurs.getModel();
            tableModel.setRowCount(0);

            while (result.next()) {
                Object[] util = new Object[9];
                util[0] = result.getString("id");
                util[1] = result.getString("nom");
                util[2] = result.getString("prenom");
                util[3] = result.getString("login");
                util[4] = result.getString("mdp");
                util[5] = result.getString("adresse");
                util[6] = result.getString("cp");
                util[7] = result.getString("ville");
                util[8] = result.getDate("dateEmbauche");

                tableModel.addRow(util);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AccesBdD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTextRechercheActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        FenetreAjouter FenetreAjouter = new FenetreAjouter();
        FenetreAjouter.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        try {
            for (int i = 0; i < tableUtilisateurs.getRowCount(); i++) {
                String id = tableUtilisateurs.getValueAt(i, 0).toString();
                String nom = tableUtilisateurs.getValueAt(i, 1).toString();
                String prenom = tableUtilisateurs.getValueAt(i, 2).toString();
                String login = tableUtilisateurs.getValueAt(i, 3).toString();
                String adresse = tableUtilisateurs.getValueAt(i, 4).toString();
                String cp = tableUtilisateurs.getValueAt(i, 5).toString();
                String ville = tableUtilisateurs.getValueAt(i, 6).toString();
                String dateEmbauche = tableUtilisateurs.getValueAt(i, 7).toString();

                String sql = "UPDATE utilisateur SET nom = ?, prenom = ?, login = ?, adresse = ?, cp = ?, ville = ?, dateEmbauche = ? WHERE id = ?";
                PreparedStatement statement = accesBdD.getConnexion().prepareStatement(sql);

                statement.setString(1, nom);
                statement.setString(2, prenom);
                statement.setString(3, login);
                statement.setString(4, adresse);
                statement.setString(5, cp);
                statement.setString(6, ville);

                try {
                    statement.setDate(7, java.sql.Date.valueOf(dateEmbauche));
                } catch (IllegalArgumentException e) {
                    JOptionPane.showMessageDialog(this, "Date invalide pour l'utilisateur avec ID : " + id, "Erreur de date", JOptionPane.ERROR_MESSAGE);
                    continue; // Passer à la ligne suivante
                }

                statement.setString(8, id);

                int rowsUpdated = statement.executeUpdate();
            }

            JOptionPane.showMessageDialog(this, "Mises à jour terminées avec succès !");
        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur lors de la mise à jour des utilisateurs : " + e.getMessage(), "Erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTextRechercheFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRechercheFocusGained
        if (jTextRecherche.getText().equals("Rechercher : ")) {
        jTextRecherche.setText("");
        jTextRecherche.setForeground(Color.BLACK );
    }
    }//GEN-LAST:event_jTextRechercheFocusGained

    private void jTextRechercheFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextRechercheFocusLost
        if (jTextRecherche.getText().isEmpty()) {
        jTextRecherche.setText("Rechercher : ");
        jTextRecherche.setForeground(Color.BLACK);
    }
    }//GEN-LAST:event_jTextRechercheFocusLost

    private void jButtonRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetourActionPerformed
        FenetreMenu FenetreMenu = new FenetreMenu();
        FenetreMenu.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreConsulter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreConsulter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextRecherche;
    private javax.swing.JTable tableUtilisateurs;
    // End of variables declaration//GEN-END:variables

}
